name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-react:
    name: Build React App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend  
      
      - name: Build React App
        run: npm run build
        working-directory: ./frontend
      
      # Uncomment these lines if you want to run tests for React
      - name: Run tests
        run: npm test
        working-directory: ./frontend

  build-nestjs:
    name: Build Nest.js API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend  

      - name: Build Nest.js API
        run: npm run build # Build 명령 사용
        working-directory: ./backend

      # Uncomment these lines if you want to run tests for Nest.js
      - name: Run tests
        run: npm test
        working-directory: ./backend
